"""8d-user-model-confirmed-attribute

Revision ID: 5a4f60e4fe44
Revises: 71b7e64848b7
Create Date: 2019-08-27 16:22:12.244221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4f60e4fe44'
down_revision = '71b7e64848b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
